### ISSUE TITLE
calculus, and discrete mathematics, algorithms

### ISSUE THREAD

**Issue by Buzzlightyear90** [open-source-society/computer-science#139]
This is just a suggestion but I may be wrong. Before learning Algorithms, I know understanding discrete mathematics is important but in order to understand discrete mathematics, i'm sure you also need to understand calculus. I thought in one of the MIT algorithm course, the prerequisites were understanding multivariable calculus. I thought if it is possible to rearrange the calculus portion to come before discrete mathematics instead of later. I may be wrong or not but I thought it could be a suggestion.

**Comment by cbmira01** [comment]
Actually, calculus and discrete math can be taught in no particular order. Calculus uses arguments based on continuous (or mostly so) functions, while discrete math makes counting arguments on the set of natural numbers. 

After four semesters of calculus, semesters of linear algebra and differential equations, and two semesters of real analysis, I found discrete math much more difficult. This difficulty extended into probability, because you had to (at times) make exhaustive counting arguments for discrete event spaces. I never got used to that for some reason...

**Comment by oharrison** [comment]
According to the MIT OCW,

High School Algebra and Trig. < Single Variable Calculus < Mathematics for Computer Science < Intro. to Algorithms

**Comment by ericdouglas** [comment]
@Buzzlightyear90 as  @cbmira01 said, Calculus doesn't is a prerequisite for DM. I already took those classes and they are not correlated, IMHO.

Calculus is a big section, and I let this in the middle of our curriculum because in that way students will be able to create interesting practical stuff with those abstract classes, knowing a lot about programming.

@oharrison thank you for pointing that out!
