### ISSUE TITLE
Community Building Ideas and Discussions

### ISSUE THREAD

**Issue by oharrison** [open-source-society/computer-science#148]
I think its about time we start thinking about building a more robust community around OSS University. I am really fond of this initiative, and I would like to see it become a very successful project. When it comes to learning online, I think one of the challenges that the MOOC revolution is facing is that online learners often times feel as if they are studying alone (despite the efforts on each platform to encourage discussions). Another issue is that many of the MOOCs being taken here are self-assessed. The problem with that is that students may not be receiving quality, frequent, and/or sufficient feedback. I think that building a community would begin to address these issues. 

The last thing we want is for someone to start the program, get halfway through a single MOOC, think that the entire curriculum is too difficult or worse that they aren't smart enough, and quit. 

I would suggest taking a look at how <a href="http://freecodecamp.com">FreeCodeCamp</a> went about building their community. I think that it has worked quite well so far. As I am typing this, 117,859  campers have joined FreeCodeCamp since they launched 362  days ago. How many actually complete the program, I do not know. But, I can say that I've stuck with the program in part because of how great I think the community is.

Right now we have nearly 1000 students signed up, and it would be a waste to let any of them fall by the wayside.

I notice that we currently have Gitter chat, a facebook page, and a subreddit. That's great. We could create additional gitter rooms for each section of the curriculum, perhaps begin working on a web site (I don't know if the ossu-ui project is going to be our website and mobile application), and a blog is an awesome way that students can share the materials they are finding helpful. We could also encourage local meetups as the number of students increase. These are just ideas to spark a discussion and keep in mind.

**Comment by mseyne** [comment]
I agree with you @oharrison and I think the dev team is working on the technical side and they are inspired by project like FreeCodeCamp. Ossu-ui will be both. The blog to share document and resources is also planned :)

On the side non-technical, I hope there will be local meetups and support groups in the same time the community grow. Thanks for the spark :+1:

**Comment by Dashed** [comment]
One (hypothetical) idea I'd like to throw around is being able to collaborate/share flashcards (in the form of `JSON` files) through GitHub (or some place to share files). Does OSS have something similar planned?

I'm currently developing and dog feeding a flashcard app (https://github.com/Dashed/grokdb) as a motivation for learning the go language. At the moment, I'm using it for computer science courses I'm taking at University of Toronto.

**Comment by bestknighter** [comment]
@oharrison I agree with you and I have one idea to add! In our website or blog (when we have one of them) we could add a section called "Community Spotlight" where can be posted from time to time (maybe weekly) a testimonial from a student or group of student (written by themselves, of course), projects that was developed and became trending, interviews, and so on. The amount of content we can place in this are big and I think that you got the idea. We can even add a button for "Submit your own story!".

**Comment by oharrison** [comment]
@Dashed thank you for your suggestion. I will take a look at your flash card project. I might event send a pull request. 
@bestknighter I like this idea. It good to see the stories of people who have struggled and "made it."

**Comment by ericdouglas** [comment]
@oharrison thank you for your kind words.

I agree with all the suggestions that you guys said.

In fact, our reddit subchannel is a quite powerful way to show what we are doing, but we need adherence by the community showing their projects and discussing their progress in such channel.

If some of you have an interest in becoming an OSS community manager, just let us know.

We'd love to have more help in such position because keep people motivated is one of the core features that we need to offer and always improve, as well as you pointed, @oharrison .

**Comment by prashcr** [comment]
Looking at the FreeCodeCamp model, I think there's one important thing to take away. When they first started, most of their tutorials were sourced from other sites. What really added value to FreeCodeCamp apart from the community and the tutorials was the list of solid project ideas that users have to complete. 

While a lot of people here at OSS highly encourage project-based learning, it all seems to be along the lines of "Be creative, do whatever you want". There is definitely value in that. But a lot of people might not be able to find an idea that they're willing to pursue and stick with. Learners tend to have trouble finding ideas in the first place, or they might think of ideas that are too complicated for the stage of learning they're at. Which is why it really helps to be given a couple of concrete ideas to implement from scratch using skills you've learnt. From my personal experience with FCC, it really helped me with learning web dev.

Since everything here is nicely divided up into sections, I think we should add one project that students should do, per section.

**Comment by bestknighter** [comment]
@prashcr We have a link to some projects suggestions on the [readme](/open-source-society/computer-science/blob/master/README.md) to the students. But reading your comment I noticed that we can add at the end of each category a list (or a link to a list) of those projects that the student can already accomplish. But I think that we should reinforce in those lists that the student must develop their creativity and start a project from the scratch and with his own project idea. Creativity is one of the most important skills nowadays and we should do our best to help everybody develop the creativity.

**Comment by prashcr** [comment]
@bestknighter I don't think we need to reinforce the need to develop creativity, Creativity tends to flow naturally once students gain confidence in their abilities and that's what we should focus on IMO.

Ah, I didn't really notice those suggestions...:sweat_smile: 
Which kind of leads back to the main point, that we need to make them more prominent.

The project suggestions are nice for further learning (after completing) and should remain there for that purpose. But for the actual learning process itself, we should narrow down a couple of compulsory projects. Otherwise students will just look at the list and get overwhelmed by the choices. This is one of the main philosophies at FreeCodeCamp, and it's been serving them quite well. Reduce choices where possible and keep the curriculum streamlined, with only the most important materials.  
Learning to program can be a frustrating [rabbit hole](http://www.businessinsider.com/learning-how-to-code-imposter-syndrome-2014-11), and we shouldn't be making things harder for students.

**Comment by bestknighter** [comment]
@prashcr At least in my country, more than 80% of the population has a mindset that thinks that creativity is an innate skill. Or you born creative or you'll never be. Which is completely false, as you know. So, even when they get the abilities, the creativity doesn't flow because they don't let the creativity "born" in their minds. If the students can think of a good project idea by themselves and make it happen, this boosts their confidence more than give a project already ready and proved that works to them just implement. If they do just a simple and plain notepad program (even if they know the existence of Notepad++), if they come with the idea by themselves, it will have a batter impact if we give them a simpler version of Notepad++ for them to implement. We want to build creators, builders, inventors, not plain programmers. I'm saying this by my own life experience. People who know how to program gets jobs. People who can create, build, with the computation gets the best jobs. So, IMO, help students to be creative is something that we should do.

But I'm not saying that we should keep everything open and free and the students do whatever they want, when they want, how they want. Overwhelming in any area is a dangerous poison to learning. We must indeed address this issue but I think that we should do in another way. My suggestion, based in later messages here and this one, is the following:

At the end of each section, we should suggest just a few projects for the student do at the end of that section that is hard enough to exercise the knowledge learned but not too hard to avoid overwhelming. But always remembering them that being creative is important and thinking on a project idea (preferably as hard as the suggested ones) by themselves is desired, encouraged and it can be inspired by the suggested ones.

**Comment by prashcr** [comment]
@bestknighter Hmm, in response to your Notepad example. I don't think it's fair to say that telling someone to make a Notepad clone doesn't help with creativity. Given the task of "Make a Notepad app", there are so many architectural, design, feature decisions that a student has to make, which involve heavy creative thinking. Just because we provide one or more user stories doesn't rob the task of creativity. In addition, students can still go out of their way and make the notepad do really cool things that weren't part of the spec.

Your suggestion sounds good. In addition, students could be required to do one of projects required and the 2nd one could be a choice between their own idea or another suggested project

**Comment by ericdouglas** [comment]
@prashcr we've covered the point that you're talking about, "*give students some project ideas*". There are two repositories with this finality.

Now the only thing that we need to do is to create more project ideas and send for those repositories.

Students need to start to think by themselves, and for me is much better to invest time struggling in how to apply the knowledge acquired in a practical project than waste the same amount of time memorizing topics in order to take exams.

Yes, this is a totally disruptive approach, but I'm sure that this will lead us to produce better professionals, with balanced pragmatic and theoretical skills.

**Comment by Dashed** [comment]
Any chance for the forum to be on Discourse rather than Google Groups? Example: https://discuss.reactjs.org/

**Comment by ericdouglas** [comment]
@Dashed We already discussed it in a previous issue. We've chosen Reddit, instead. In that way, we don't need to spend money with servers.
