### ISSUE TITLE
Mathematics for Computer Science has a calculus prerequisite

### ISSUE THREAD

**Issue by jakecraige** [open-source-society/computer-science#202]
On [the syllabus for Mathematics for Computer Science](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-fall-2010/Syllabus/) it says that the [Single Variable Calculus](http://ocw.mit.edu/courses/mathematics/18-01-single-variable-calculus-fall-2006/) course is a prerequisite. 

Should the curriculum be re-ordered to have at least Calculus 1 before this course?

**Comment by ericdouglas** [comment]
Hey, @jakecraige ! 

We already discussed this [here](https://github.com/open-source-society/computer-science/issues/139).

Here we're proposing a new approach for students' education, a linear one, so inevitably this will have some pros and cons.

I prefer to keep those calculus courses after some programming sections because in that way students will be able to create more interesting projects with such Math knowledge. :smile:
