### ISSUE TITLE
Some courses are closed

### ISSUE THREAD

**Issue by x-ji** [open-source-society/computer-science#211]
For example the course for Natural Language Processing by Stanford at Coursera https://www.coursera.org/course/nlp is not open to enrollment now and the date for next iteration (or whether there would be any next iteration at all) is uncertain. On the contrary a similar course by Columbia seems to be still open https://www.coursera.org/course/nlangp. I suspect this is also the case for some other courses listed here.

**Comment by ericdouglas** [comment]
@x-ji 

from our [FAQ](https://github.com/open-source-society/help/blob/master/FAQ.md) file:

> **Q** : Some of the courses appear to be closed and there doesn't seem to be a way to access their content! What should I do?
>
> **A** : Though we encourage Self-paced learning, some courses are closed by the MOOC platform and are only open at certain time intervals. We suggest you check them right now and register for the courses even if you won't complete them now. Once you've registered you should have access to most of the material even after the course officially ends. If you see that one of the courses is starting soon, don't hesitate to tell the community about it. (For example: the automata course on coursera is open until 6 november 2015) Again, you should consider enrolling now for all of the open courses you plan to do in the future as the course could be closed later.

**Comment by x-ji** [comment]
Sure. The thing is that for this course the materials are not accessible any more now that it's closed, and it only shows "future sessions" without an option to enroll.

Have you guys taken a look at the course https://www.coursera.org/course/nlangp whose materials are still accessible even though it's finished? Is there any reason the course by Stanford is considered better than this course by Columbia. If not then I guess you might list this course as a viable alternative.

**Comment by ericdouglas** [comment]
@x-ji 

you can indeed access the previous material [here](https://class.coursera.org/nlp/lecture/preview).

But I think that you caught a mistake here. The actual course should be the one provided by Columbia University because it is always open. In an older version of this curriculum, we were listing both courses.

Another reason for choose the Columbia University course is that it seems a bit more complete than the one from Stanford.

You can see that in the "Duration" column already are stating that the duration is 10 weeks, and the course from Stanford has 8 weeks for duration.

Thank you so much for open this issue, I'll update our curriculum to point to the correct course. :smile:
