### ISSUE TITLE
Expired Courses

### ISSUE THREAD

**Issue by deper29** [open-source-society/computer-science#231]
edX locks out courses after a period of time and doesn't always archive them for viewing later. Is it possible to make changes to the syllabus to instead include classes that are available year round?

**Comment by bryan8392** [comment]
I have come across this as well. Any alternatives to Introduction to Computational Thinking and Data Science (https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-2#!)?

**Comment by wxt2005** [comment]
I think I missed [6.00.2x](https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-2#!) either..... Does anyone have alternative choices?

**Comment by jakecraige** [comment]
I've also run into this. Thankfully since I'm not doing verified certificates and was working on other courses, I'm able to enroll even if I'm not actively participating so I have access to the archived course after, when I do have time.

Given that this is a problem it would be nice to have alternatives offered when these courses are not readily available when the student is ready to take them.

**Comment by deper29** [comment]
I'm referring to courses that don't get archived or aren't archived anymore. 6.00.2x was the example at the time, but I believe there were a few others.

**Comment by bender3** [comment]
This doesn't solve the issue but for those who missed on 6.00.2x you could check [HERE](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/unit-2/) - I belive this was the original course, later adapted to edX. 

I'm actually following 6.00.1x from there since I have a lot of free time and don't want to wait 1 week for the content to become available.. hope it's not "against the rules"

**Comment by wxt2005** [comment]
Hey guys, I found [6.00.2x](https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-3#!) was opened for enrollment.

**Comment by ericdouglas** [comment]
The way to go IMO is to enroll in all open courses and do the course after with the archived material.

Another option is our [extras section](https://github.com/open-source-society/computer-science/tree/master/extras), that is a place where our students will be able to make suggestions.
