### ISSUE TITLE
Repurposing of books.md

### ISSUE THREAD

**Issue by johnaoss** [open-source-society/computer-science#333]
Currently, the OSS Curriculum is meant to be a **free** open source curriculum to learn about computer science. As of the creation of this issue, none of the books are free, which closes off this section to only a select, paying few. 

I think that it'd serve the community much better if it was populated with links to online textbooks, that are available for free, with a separate section for physical/non-free books. 

Thoughts?

**Comment by jimages** [comment]
I agree with John. I think the books should be free/open source in order to
be a free curriculum. But the free books are rare and the books may be not
as good as non-free books. So  I also suggest add two sections. One is
free/open source books. The other is non-free books.

On Thu, Jun 30, 2016 at 10:39 AM, John Oss <notifications@github.com> wrote:

> Currently, the OSS Curriculum is meant to be a *free* open source
> curriculum to learn about computer science. As of the creation of this
> issue, none of the books are free, which closes off this section to only a
> select, paying few.
>
> I think that it'd serve the community much better if it was populated with
> links to online textbooks, that are available for free, with a separate
> section for physical/non-free books.
>
> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-source-society/computer-science/issues/333>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABsxUWgc1aEjd7U--CVFBcXWRl0LEU57ks5qQyxcgaJpZM4JBv-u>
> .
>



-- 
Happy good life.

**Comment by ericdouglas** [comment]
@johnaoss @jimages thank you so much for pointing this out. 

It makes total sense and now it's already fixed. :smile: :pray:

**Comment by jeremypearson** [comment]
@ericdouglas @johnaoss @jimages I partially agree with @jimages: but instead of having two separate lists, I think it should just be said next to the reason in brackets whether the resource is free or not. I think it's completely fine to put paid textbooks in the list though, since the list is in the "extras" folder. In my opinion, since it's in the "extras" folder, it shouldn't have to strictly follow the "it needs to be free" rule. But definitely saying whether it's free or paid next to it would be helpful.

**Comment by jeremypearson** [comment]
Resource*
