### ISSUE TITLE
Course About robotics?

### ISSUE THREAD

**Issue by YasserKa** [open-source-society/computer-science#378]
Won't robotics be a good addition to the list?

**Comment by benbrandt** [comment]
Do you have any courses you recommend? 

Also, I looked through the curriculum's from a few different schools and, at least at the undergrad level, they don't usually offer courses in robotics for the CS degree.

@ericdouglas what criteria do you use to decide if a topic should be added to the curriculum?

**Comment by YasserKa** [comment]
Well, I didn't make this suggestion as someone who knows about robotics. In fact, I didn't take a single robotic course yet. Although, I think some people would love to have an insight of such domain. I myself want someone to recommend me a course.

**Comment by ericdouglas** [comment]
@benbrandt I used [these](https://github.com/open-source-society/computer-science#references) references and I also looked several curriculums.

@YasserKa I don't believe this topic is a good one to have in our main curriculum because it'll require student invest some money to buy the hardware in order to create something, and it could be a little expensive and/or hard to find.

**Comment by Heasummn** [comment]
I think embedded programming is slowly coming to become a very major part of Software Engineering. Learning embedded programming and robotics would be a major addition to the curriculum.

There are a couple of solutions to students needing to buy hardware.  One of them is to use a hardware simulator, or an environment for embedded programming. 

Unfortunately, these usually aren't as good as actual, physical hardware. 

Embedded programming/Robotics is also one of the fields where it's probably better to just get down and dirty with a manual rather than following a course, so it might not be suited for our curriculum.
