### ISSUE TITLE
Having trouble logging in

### ISSUE THREAD

**Issue by Nedu** [open-source-society/computer-science#395]
I'm having trouble logging into the firebase app using github. It authenticates but I still cant get in

**Comment by MohammedAttya2** [comment]
I just tried to log in now and it succeeded

**Comment by Nedu** [comment]
I'm not sure why it's not working for me, its been going on for like a week now

**Comment by ericdouglas** [comment]
@Nedu we stopped to use/support the web app a long time ago for several reasons, and one of them is because students frequently were having problems like yours.

We are now suggesting students to use Trello to track their progress. You can see more about it [here](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress).

If you have any doubt don't hesitate to ask.

**Comment by 199522** [comment]
HALO,
Am also finding problem with finding what to read, i registered for
computer science
Any help will be useful
Thanks

**Comment by mourackb** [comment]
Helllo @199522,

please read the   @ericdouglas comments.

"@Nedu we stopped to use/support the web app a long time ago for several reasons, and one of them is because students frequently were having problems like yours.

We are now suggesting students to use Trello to track their progress. You can see more about it here.

If you have any doubt don't hesitate to ask."
