### ISSUE TITLE
Differences between older link and current

### ISSUE THREAD

**Issue by alwongg** [open-source-society/computer-science#398]
Older link: https://github.com/open-source-society/computer-science/blob/8a52c2ad6e5f45cd831811b5e100b8bd4e1f7977/README.md#project-suggestions

Current link: https://github.com/open-source-society/computer-science

There are courses missing from the older link in comparison to the newer such as Software testing and Software Processes and Agile Practices are missing in the current curriculum. And most importantly the algorithms course went from the Princeton to Standford courses. Just wanted to know if these changes are okay in missing out on software testing and agile practices for example. What are your thoughts? 

Thanks!

**Comment by hanjiexi** [comment]
Hello, thank you for pointing out the omission of Software Testing. It had originally been removed when I started revising the curriculum, but my revisions have evolved since then to the point that I'm open to adding it back in under [Advanced programming](https://github.com/open-source-society/computer-science#advanced-programming) if others agree it is worth having.

Regarding the Agile Practices course, I removed it because I wanted to keep the curriculum focused on pure computer science, and that was straying too far towards the management side. Human-computer interaction courses (e.g. the UX Design course) were also removed for this same reason.

I think the answer for these non-pure CS courses is to have specialization tracks that cover these in greater depth. My current thinking is that you can look at Advanced CS as a specialization track for those deeply interested in computer science, and in the future there could be alternative specialization tracks, like Software Management, Design, [Game Development](https://github.com/open-source-society/game-development), etc., which people less interested in hardcore CS could choose after they've learned the basics from Core CS. But whether this would work depends on availability of coursework in these areas. For right now, the best option for people who want to learn this stuff on top of pure CS is to take one of the Coursera/edX/Udacity specializations/series.

The Princeton Algorithms courses were replaced with the Stanford Algorithms courses because [Part II of the Princeton courses](https://www.coursera.org/learn/algorithms-part2) is perpetually unavailable (it has said "Coming soon" for as long as I can remember). It's unclear if it will ever be offered again. The rule for anything in Core CS is that the courses have to be available, either right now or at a clearly indicated date in the near future.

**Comment by waciumawanjohi** [comment]
Can the Algorithms 1/4 and 2/4 links change to the Stanford Lagunitas version? Same content available free from Stanford's online course platform.

**Comment by hanjiexi** [comment]
Well as the Lagunitas version only covers half of the material of the Coursera version I don't want to remove the Coursera links, especially as the lectures in both versions are free of charge to access. But what I can do is to add a note with a link to the Lagunitas version of 1/4 and 2/4 stating that the Lagunitas version has free-to-access quizzes and assignments for those topics.
