### ISSUE TITLE
all needs to include ratings, structured meticulously from easiest to hardest

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [open-source-society/computer-science#401]
* courses/classes needs to include ratings

it's good not to spread low quality info in society

i have a non-complete version i made for myself from 'for actual beginners to progressive harder'

can i please help you make this significantly better?

**Comment by li-xinyang** [comment]
I do not think the rating is necessary for the curriculum and the reason is obvious. The rating is for comparison similar things OR courses in our case and the curriculum should not include multiple courses covers similar topic(s).

All courses provided here are **not** low quality (please comment below if you think any of the course listed here is a low-quality course).

I think the version 7.x is a great starting point for either beginners or any programmer who do not have a CS degree

> i have a non-complete version i made for myself from 'for actual beginners to progressive harder'

I would love to take a look at your version if you can provide a link for it.

**Comment by srs1978** [comment]
Ratings are going to be super subjective anyways.

**Comment by ericdouglas** [comment]
Like @li-xinyang well said, all courses provided here are not low quality, so add this kind of information won't be useful at all.
