### ISSUE TITLE
No recommended Mechanics (aka intro physics w/ calc) course as a prerequisite to Electricity and Magnetism

### ISSUE THREAD

**Issue by nofawkesgiven** [open-source-society/computer-science#402]
As the title says, there is a prerequisite requirement for Mechanics before taking Electricity and Magnetism I. To remedy this, I've signed myself up for MITs Mechanics ReView on edx, since they allow a broad use of textbooks and it seemed to have favorable reviews. It is an archived course though, so I'm unsure if it belongs in this curriculum.

**Comment by srs1978** [comment]
I think the assumption is that one graduated with a normal complete secondary education which would include mechanics.

**Comment by srs1978** [comment]
From the document: 

> Core CS assumes the student has already taken high school math and physics, including algebra, geometry, and pre-calculus. Some high school graduates will have already taken AP Calculus, but this is usually only about 3/4 of a college calculus class, so the calculus courses in the curriculum are still recommended.

**Comment by hanjiexi** [comment]
Yep, it's not included because it's assumed the student has at least some prior background (without this assumption, we'd have to include courses stretching back all the way to elementary math). I'm still on the lookout, however, for a specific, high-quality and highly complete course to recommend for getting whatever knowledge is missing between basic high school physics and electricity and magnetism. I'm not sure if the MIT Mechanics ReView quite fits this requirement or not. From the description it sounds like it's for people who have already taken mechanics.

**Comment by CgJesus** [comment]
You might want to have a look at Landau theoretical physics courses (that includes mechanics)
https://en.wikipedia.org/wiki/Course_of_Theoretical_Physics

**Comment by hanjiexi** [comment]
Added [FAQ entry](https://github.com/open-source-society/computer-science/blob/master/FAQ.md#why-is-the-curriculum-missing-some-pre-requisites) explaining why there's no basic physics course.
