### ISSUE TITLE
Algorithms courses appear to be trial only

### ISSUE THREAD

**Issue by jonathanmonreal** [open-source-society/computer-science#407]
The Coursera versions of the algorithms courses appear to have gone to a 7-day trial only with no open enrollment. The Stanford version of the first two courses is still available.

**Comment by li-xinyang** [comment]
Can you provide a link for the course you are talking about (the one with 7-day trail only)?

**Comment by jonathanmonreal** [comment]
The links are exactly the same as the ones listed on the curriculum page. Here's one example for [https://www.coursera.org/learn/algorithms-divide-conquer](https://www.coursera.org/learn/algorithms-divide-conquer):

<img width="1440" alt="issue1" src="https://cloud.githubusercontent.com/assets/10861488/26137672/f3c20a28-3a80-11e7-869d-44765dbe5629.png">

Based on the text on that page, it does not appear to be available for free on a permanent basis.

**Comment by li-xinyang** [comment]
I can enroll the course without any restriction and I am not sure why we have two different views for this course.

<img width="826" alt="screen shot 2017-05-17 at 12 54 05 pm" src="https://cloud.githubusercontent.com/assets/3349406/26138998/05c1c1bc-3b00-11e7-9f45-56381f710e38.png">

However, just for your information, the same course can also be found at Stanford Online Site (see link below).

https://lagunita.stanford.edu/courses/course-v1:Engineering+Algorithms1+SelfPaced/about

If you are not comfortable taking the course via Coursera try Standford Online

**Comment by jonathanmonreal** [comment]
Are you maybe not logged in when looking at that screen? I get the same thing when I'm logged out, but when I click the "Enroll Now" button and sign in this modal comes up:

<img width="718" alt="issue2" src="https://cloud.githubusercontent.com/assets/10861488/26139417/c3215f42-3a8d-11e7-8b83-1047816c064d.png">

Thanks for the suggestion. Unfortunately, I get the same thing for the two algorithms classes that are not offered on Stanford's website.

**Comment by li-xinyang** [comment]
I cannot see your page because I have enrolled this course before. I try to unenroll from the course but I am still seeing the same page.

<img width="1674" alt="screen shot 2017-05-17 at 1 24 14 pm" src="https://cloud.githubusercontent.com/assets/3349406/26139572/490d4eb0-3b04-11e7-80ce-24405b2e0553.png">

Coursera site sometime can be buggy and annoying.

**Comment by hanjiexi** [comment]
Thanks @li-xinyang for helping, and you're right Coursera is very annoying. I would even call their course enrollment process a [dark pattern](https://darkpatterns.org/) with that tiny "audit" link at the bottom. As I don't see other platforms stepping up to offer everything Coursera provides, we're stuck with it for the time being, so maybe instructions need to be added to the curriculum to help people with this process.

@jonathanmonreal Let us know if you were able to audit the course properly, and I apologize for the confusing nature of the enrollment process.

**Comment by jonathanmonreal** [comment]
@hanjiexi It was actually pretty late in my time zone by the time I clicked on the modal which probably didn't help, but I didn't even recognize the audit link as being distinct from the trial at the time. I think some kind of note would be helpful.

@li-xinyang Thank you for all the help. The enrollment worked just fine, so I'm closing the issue.

**Comment by GregoryGoncalves** [comment]
@li-xinyang 

This course seems to only be available for a price.
https://www.coursera.org/specializations/full-stack#pricing

**Comment by li-xinyang** [comment]
@GregoryGoncalves It is NOT a course, it is a specialization. 

Specialization is a combo (a mini curriculum) which contains launched courses. In order to do the specialization for free, you have to search individual course and then you can audit it for free.

Btw I have completed the entire specialization for free, not a fan for the content.

<img width="1393" alt="screen shot 2017-07-16 at 09 45 25" src="https://user-images.githubusercontent.com/3349406/28243850-d5509248-6a0b-11e7-8bc0-5636de76d7fe.png">

**Comment by TYRONEMICHAEL** [comment]
@li-xinyang curios as to why you were not a fan of the content. I am actually just about to begin the courses and am quite fond about learning algorithms well. Are there other resources, free or paid you would recommend?

**Comment by li-xinyang** [comment]
@TYRONEMICHAEL I am not a fan for this specialization (https://www.coursera.org/specializations/full-stack) the reason is the course is outdated (Angular v1.x.x) and the course basically is a reformated version of the documentation (What's CSS/HTML/JavaScript/Bootstrap/etc.). 

Basically, I think the courses cover technologies/technical skills (framework/lib usage, the skill used to find a job, the skill used to apply immeadiately) should be learned from other channels instead of learning from University courses.

Of course, those learning Algorithms and the fundamental/advanced knowledge of any kind university course is an excellent choice.
