### ISSUE TITLE
Add difficulty/workload columnt to each course

### ISSUE THREAD

**Issue by balta2ar** [open-source-society/computer-science#99]
To estimate how difficult a course is, I suggest adding difficulty and workload per week columns to each course.

**Comment by ericdouglas** [comment]
@balta2ar thanks for pointing that out. Now that you made this suggestion, I'm wondering, maybe we can remove all references for the time that the student should spend in each course.

**Why**?

Because the whole point here is to acquire knowledge, and students will have different situations. Some won't be able to dedicate X hours, or worst than it, some will be able to dedicate 2X hours for week, but because we are recommending X hours, they will do just it.

I think that we can instigate students to take their time, and complete each course as perfectly as they can, without worrying about time.

If we spent a whole year in just one course, what is the problem??? We'll master this topic, in such case. 

The pace of each course, for me, should be a personal decision, based on internal motivation.

What are your thoughts about it?

ps: the student still have informations about the recommend time to dedicate in the page of the course.

**Comment by svenluijten** [comment]
+1. The estimated time to spend on a course can turn some people away, effectively scaring them off. Difficulty level would be a welcome addition :+1:

**Comment by ericdouglas** [comment]
@svenluijten with such thing in mind, wouldn't be better remove the Duration column? So just the Course column should remain. 

Because if you can't spend 15 hours/week, such information will turns people away in the same way.

**Comment by svenluijten** [comment]
@ericdouglas Yeah, I was thinking to remove the duration, and create a new "difficulty" column.

**Comment by ericdouglas** [comment]
@svenluijten I agree! We just need to stipulate a criteria for such categorization.

**Comment by balta2ar** [comment]
Well, we're grown-ups after all. Duration, difficulty, workload are just slightly different estimations of how involved the course is. Say, I'm interested in hardcore, practical, time-consuming through in-depth courses with programming assignments. Knowing the difficulty in advance I can take two courses at a time. On the other hand, if you withhold the actual difficulty, the student might get disappointed later when she finds out it does not match her expectations.

Another categorization type worth adding, I think, is the balance of how practical/theoretical the course is.

**Comment by ericdouglas** [comment]
Here we're proposing a linear approach, and I think that is a better idea schedule a portion of time to dedicate everyday to study.

If you've 2 hours/day, do the course in those 2 hours, regardless the difficulty of the course. If it is easy, you'll finish in 2 weeks, if it is hard, you'll finish in 6 weeks.

This is a much more easy approach, IMHO.

The real point to succeed is not commit to a goal, but **create discipline**.

If you are able to dedicate 1 ~ 2 hours/day, after you acquire this habit, you'll be able to finish the curriculum, independently to how much time do you will take to accomplish it.

**Comment by maicoqb** [comment]
+1 
As said by @svenluijten, the long time can turn people away.

**Comment by ericdouglas** [comment]
I removed the Duration section and also updated [this](https://github.com/open-source-society/computer-science#duration-of-the-project) paragraph on the Duration of the project section.

I think this makes a lot of sense.

**Comment by Ebisu77** [comment]
I disagree. I think people in this field are capable of making their decisions and withholding information about courses length just seems wrong. If somebody wants to be a programmer he can not be scared by education length, since it will be whole-life education anyway. We should keep information there, maybe call it "estimated length" and point out clearly that everybody can have his own pace based on his possibilities. Maybe we should say the length is based on info from course syllabus but doing them in OSSU order might cut the time down, because they are in logical order. But I don´t think people are as easily scared as you anticipate and for me when I saw those lengths I was happy that somebody is finally doing "long term plan" and not only random collection of free courses.  
 
Difficulty level as extra column is great idea.

**Comment by ericdouglas** [comment]
@Ebisu77 for now, I just hid the Duration column, but the information still is in the file.

One reason to not put duration and effort estimation here is because that information is in the course page.

Following the DRY principle (Don't Repeat Yourself).

But I also agree that the time should not scare anyone, and if so, is a good thing, because this field obligates you to always keep studying.

I would love to see how do you think we should display that.

**Comment by ericdouglas** [comment]
What do you think about this format:

Course | Duration | Effort | Required
:--|:--:|:--:|:--:
Course number 1| 8 weeks | 8-10h/week| `true`
Course number 2| 4-6 weeks | 3h/week| `false`

**Comment by balta2ar** [comment]
Course providers sometimes put difficulty level into course description (coursera, udacity). Can they be copied here when available?

**Comment by ericdouglas** [comment]
@balta2ar Do you have an example?

**Comment by balta2ar** [comment]
Coursera has difficulty level for some of the specilizations: https://www.coursera.org/specializations/data-science -- Intermediate in this case.

Udacity grades all (looks like) of their courses: https://www.udacity.com/courses/all

Edx grades their courses: https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-2 -- Intermediate

**Comment by maicoqb** [comment]
@ericdouglas let the Required column, without add more courses.
Is just to have an idea about the 'requirement'.
I think this is a good idea.

**Comment by balta2ar** [comment]
I'm not sure whether github markdown allows that, but if you like the idea of adding difficulty, instead of additional column, rows can be coloured appropriately: e.g. green, yellow, red for easy, intermediate and advanced levels.

Either difficulty or practice/theory orientation can be coloured like that. For example, check out how lectures are coloured in the syllabus of this course: https://work.caltech.edu/telecourse.html

**Comment by maicoqb** [comment]
Hey, based on site rating, I get this:

Course|Dificult
:--|:--:
Introduction to Computer Science|Introductory
Introduction to Computer Science and Programming Using Python|Introductory
Introduction to Computational Thinking and Data Science|Intermediate
|
Systematic Program Design - Part 1: The Core Method|Introductory
Systematic Program Design - Part 2: Arbitrary Sized Data|Introductory
Introduction to Computational Thinking and Data Science|Intermediate

Coursera has not a rating of dificulty. :confused:

**Comment by ericdouglas** [comment]
@balta2ar we can't add it because is inconsistent, just few courses will have this indicator.

@maicoqb all our course will be required. We can add links for students find more courses, but here I really think that we need to stay as lean as possible.

**Comment by maicoqb** [comment]
:+1: 
>we can't add it because is inconsistent, just few courses will have this indicator.

**Comment by Heasummn** [comment]
Adding onto this issue, maybe we can make a grading based system? 

Not like A-F, but having optional courses that add "extra-credit" to the grade. And the grade is basically just the difficulty of a course?

Though this may be a bad idea.

**Comment by ericdouglas** [comment]
@Heasummn  I didn't understand what is your proposal. You can open another issue to discuss it, if you want to keep this discussion. :smile:

Anyway, I'm closing this issue because we already have our table model.
